<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class CountryFeatureTest extends TestCase
{

    use DatabaseMigrations;

    private $baseUrl = 'api/v1/';

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testCreateCountryReturnExpectedValue()
    {
        $data = [
            'code' => 'ID',
            'name' => 'Indonesia',
            'status' => true,
        ];

        $this->post($this->baseUrl . "countries", $data)
            ->assertStatus(201)
            ->assertJson($data);
    }

    public function testUpdateCountryReturnExpectedValue()
    {

    }

}
